### ISSUE TITLE
Compilation with DBG_SCALARFIELD is broken

### ISSUE THREAD

**Issue by gsell** [OPALX-project/OPAL#905]
Compilation fails after merging !655: `<filesystem>` library was not included in the header.

In addition 'format' is not a member of 'std' until C++20, so we still have to use boost.

---
_Migrated from GitLab_
GitLab ID: 811
Source: https://gitlab.psi.ch/OPAL/src/-/issues/811
Original state: closed
Original author: ext-calvo_p
